# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.4.1
_src_path: git@github.com:actuaristai/template.git
email: ''
full_name: William Lee
project_name: food_search
project_short_description: Interactive Food Search and RAG chatbot system
remote_repository: git@github.com:actuaristai/food_search.git
